name: Develop Build


on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.13
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.13
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
      - name: "Build with Gradle"
        run: ./gradlew build  # gradle does not support SNAPSHOT versions during upload to the portal https://discuss.gradle.org/t/uploading-snapshot-versions-to-the-plugin-portal/11347/8

